### ISSUE TITLE
Getting this problem on docker-compose up

### ISSUE THREAD

**Issue by ahmadalibaloch** [sergio-fry/youtube-fetcher#148]
~/youtube-fetcher(master*) » sudo sudo docker-compose up --force-recreate worker db           2 ↵ ahmad@DESKTOP-JKR0D7G
Recreating youtubefetcher_db_1 ...
Recreating youtubefetcher_db_1
Recreating youtubefetcher_memcached_1 ...
Recreating youtubefetcher_memcached_1 ... done
Recreating youtubefetcher_worker_1 ...
Recreating youtubefetcher_worker_1 ... done
Attaching to youtubefetcher_db_1, youtubefetcher_worker_1
db_1         |
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         |
db_1         | LOG:  database system was shut down at 2020-04-18 19:11:46 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
db_1         | FATAL:  database "development" does not exist
worker_1     |
worker_1     | rake aborted!
worker_1     | LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/evented_file_update_checker.rb:59:in `block in initialize'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:13:in `block in silence_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:26:in `with_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:13:in `silence_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/evented_file_update_checker.rb:57:in `initialize'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:59:in `new'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:17:in `block in <class:Railtie>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:49:in `each'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
worker_1     | /app/config/environment.rb:5:in `<top (required)>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:329:in `require_environment!'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:445:in `block in run_tasks_blocks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
worker_1     | /usr/local/bin/bundle:30:in `block in <main>'
worker_1     | /usr/local/bin/bundle:22:in `<main>'
worker_1     |
worker_1     | Caused by:
worker_1     | LoadError: cannot load such file -- listen
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/evented_file_update_checker.rb:59:in `block in initialize'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:13:in `block in silence_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:26:in `with_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/core_ext/kernel/reporting.rb:13:in `silence_warnings'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/evented_file_update_checker.rb:57:in `initialize'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:59:in `new'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/i18n_railtie.rb:17:in `block in <class:Railtie>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:49:in `each'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
worker_1     | /app/config/environment.rb:5:in `<top (required)>'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:329:in `require_environment!'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/application.rb:445:in `block in run_tasks_blocks'
worker_1     | /app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
worker_1     | /usr/local/bin/bundle:30:in `block in <main>'
worker_1     | /usr/local/bin/bundle:22:in `<main>'
worker_1     | Tasks: TOP => db:migrate => environment
worker_1     | (See full trace by running task with --trace)
youtubefetcher_worker_1 exited with code 1

**Comment by sergio-fry** [comment]
Looks like db does not exists. Could you add POSTGRES_DB=development to docker-compose.yml for a db service? DDDocs can be found here: https://hub.docker.com/_/postgres
