### ISSUE TITLE
Video Podcast

### ISSUE THREAD

**Issue by pikespeak** [sergio-fry/youtube-fetcher#49]
Nice Project,

it is possible, to get not only audio as feed?
My iPhone Client (Downcast) support Video too?

**Comment by sergio-fry** [comment]
Currently it is not. But let's schedule this feature! It would be great to have

**Comment by sergio-fry** [comment]
@pikespeak Youtube Fetcher supports video mp4 podcasts now. Check it out:

 http://youtube-fetcher.russianpulse.ru/channels/UCsT0YIqwnpJCM-mx7-gSA4Q

**Comment by pikespeak** [comment]
you are awesome. It works. THX!!!

There is noch "Video description available" shall i pull a new issue?

**Comment by sergio-fry** [comment]
@pikespeak we have one already #10
